tweaks:
  # Items can be colored in the anvil.
  anvil-color: false
  # Right-clicking an anvil with an iron block will repair it slightly.
  anvil-repair: false
  # Shift over an armor stand to quick swap armor.
  armor-swap: false
  # Right-click a bee with a beehive to capture it. Only works if the beehive is not full.
  bee-capture: false
  # Deepslate breaks instantly when mined with a netherite pickaxe, efficiency 5, and haste 2.
  break-deepslate: false
  # Protect your ender chests by picking between different break behaviors.
  break-ender-chest:
    toggle: false
    # Options:
    # - Drop (ender chests always drop, even without silk touch)
    # - Protection (ender chests cannot be broken without silk touch)
    mode: Protection
  # Glass breaks instantly when broken by the materials below.
  break-glass:
    toggle: false
    materials:
      - NETHERITE_PICKAXE
  # Breaking leaves with a hoe will break an additional block on each side. Netherite hoes will do a full 3x3x3 break.
  break-leaves: false
  # Breaking grass or flowers with a hoe will 3x3 break them. Netherite hoes will 5x5 break them.
  break-plants: false
  # Adds an indicator above mobs to show when they can breed again.
  breeding-indicator: false
  # Throw concrete powder into a cauldron to turn it into concrete.
  cauldron-concrete:
    toggle: false
    # Whether the cauldron should use a water level on conversion.
    use-water: false
  # Throw dirt into a cauldron to turn it into mud.
  cauldron-mud:
    toggle: false
    # Whether the cauldron should use a water level on conversion.
    use-water: false
  # Allows players to view their coordinates in the Action Bar.
  # This gives them permission to the '/coordinates' command to toggle it.
  coordinates: false
  # Allows players to bone meal any crop.
  crops-bone-meal: false
  # Right-click crops with a hoe to harvest them.
  crops-harvest: false
  # Prevents the trampling of crops.
  crops-protection: false
  # Notifies the dying player where they died.
  death-notify: false
  # Double doors can be opened with 1 click.
  doors-double: false
  # Allows you to open iron doors with your hand.
  # This works with the 'doors-double' option above!
  doors-iron: false
  # Right-click a cauldron to open up the drop filter.
  # Adding items to the filter prevents you from picking them up.
  # This also gives players permission to use the '/drops' command to toggle it.
  drops-filter: false
  # Breaking blocks nearby will cause their item drops to go towards the player a little.
  # This means if you are building high up, you won't lose all your drops.
  drops-magnet: false
  # Lapis stays in the lapis slot in enchanting tables when you close it.
  enchanting-lapis: false
  # Allows the dying of named mobs with dyes.
  entity-dye: false
  # If a player throws an item close to an entity, they will auto equip it.
  entity-equip: false
  # Right-click an entity with a flint & steel or fire charge to set it on fire.
  entity-ignite: false
  # If you name an entity with "silent" or "silence", it will be permanently silent.
  # To undo this, simply name the entity "unsilent" or "unsilence".
  entity-silence: false
  # Allows you to add fortune and silk touch to the same tool.
  # Right-click to swap the enchantment used.
  fortune-silk-swap:
    toggle: false
    # EXP levels required. (max: 39 levels)
    cost: 30
  # Blocks can now be placed on the top of happy ghast's heads.
  happy-ghast-placement: false
  # Happy ghasts will now fly faster than normal (only while riding).
  happy-ghast-speed:
    toggle: false
    # Speed value of riding happy ghast.
    value: 1.5
  # Right-clicking a hay bale with a hoe automatically crafts and drops bread.
  hay-bale-bread: false
  # Allows you to view the statistics (health-speed-jump) of horses by sneak-right-click.
  # This lets you find the best horses without having to tame them all first! :)
  horse-statistics: false
  # Right-clicking a crafting table in your inventory opens it.
  inventory-crafting: false
  # Allows you to add silk touch to your ender chest.
  # Right-clicking a silk touch ender chest in your inventory opens it.
  inventory-ender-chest:
    toggle: false
    # EXP levels required. (max: 39 levels)
    cost: 30
  # Right-clicking an item frame on a chest will open the chest. Shift to go back to normal behavior.
  item-frame-click-through: false
  # Shift-right-click an item frame with shears to make it invisible. Do it again to make it visible.
  item-frame-invisible: false
  # Allows you to place ladders up/down depending on your direction by right-clicking existing ladders.
  ladder-placement: false
  # Allows you to instantly climb up/down ladders.
  ladder-teleportation:
    toggle: false
    # Options:
    # - Automatic (simply walk into the ladder)
    # - Manual (look straight up/down to activate teleportation)
    control: Automatic
  # Gives players unlimited night vision if they activate it with '/nv' or '/gamma'.
  night-vision: false
  # Prevents you from attacking your own pet.
  pet-protection: false
  # Nether portals can no longer be destroyed by explosions.
  # No more ghasts or creepers destroying them!
  portal-protection: false
  # Players who join the server will have all the recipes unlocked.
  recipe-unlock-all: false
  # Sneak-right-click on farmland with a hoe to revert it back to dirt.
  revert-farmland: false
  # Sneak-right-click on dirt paths with a shovel to revert it back to dirt.
  revert-path: false
  # Sneak-right-click on a stripped log or stem to revert it back to its previous variant.
  revert-stripped: false
  # Allows you to smelt rotten flesh into leather.
  rotten-flesh-to-leather: false
  # Throwing snowballs on existing snow layers will add snow layers.
  snowballs-add-snow-layer: false
  # Throwing snowballs on plants or flowers will break them.
  snowballs-break-plants: false
  # Allows snowballs to inflict damage.
  snowballs-damage:
    toggle: false
    # Amount of damage that snowballs inflict.
    amount: 1
  # Throwing snowballs on entities will extinguish them.
  snowballs-extinguish-entities: false
  # Throwing snowballs on fire will extinguish it.
  snowballs-extinguish-fire: false
  # Throwing snowballs on water will freeze it.
  snowballs-form-ice: false
  # Throwing snowballs on any block will form snow.
  snowballs-form-snow: false
  # Changes the knockback of snowballs.
  snowballs-knockback:
    toggle: false
    # Amount of knockback that snowballs inflict.
    amount: 0.5
  # Setting a sponge on fire dries it out instantly.
  sponge-ignite: false
  # Allows you to throw torches on the ground to place them.
  # So if you throw them down a cave, it will light the block it lands on!
  torch-throw: false
  # Allows vehicles to be picked up by sneak-right-click.
  vehicle-pickup: false
  # (PAPER ONLY) Villagers will follow you if you are holding an emerald.
  villager-follow: false
  # Splashing a water bottle into lava converts it into obsidian.
  water-bottle-convert-lava: false
  # Allows you to convert a water bucket into splash water bottles.
  water-bottle-craft:
    toggle: false
    # Amount of splash water bottles you get.
    amount: 4
  # Allows weapons (swords/axes) to swing through passable blocks to hit mobs.
  weapon-swing-through: false
  # Allows the filling of empty bottles into XP bottles by right-clicking on an enchanting table.
  xp-fill:
    toggle: false
    # Amount of XP it takes to fill each bottle.
    # In vanilla Minecraft, an XP bottle drops an average of 7 experience.
    cost: 8

# Checks for any plugin updates.
update-checker:
  # Logs the update to console.
  log: true
  # Any player with the "tweaky.admin" permission will be notified of the update on join.
  notify: true

# Allows us to collect anonymous data about the plugin.
enable-metrics: true
