tweaks:
  # Items can be colored in the anvil.
  anvil-color: false
  # Right-clicking an anvil with an iron block will repair it slightly.
  anvil-repair: false
  # Shift over an armor stand to quick swap armor.
  armor-swap: false
  # Right-click a bee with a beehive to capture it. Only works if the beehive is not full.
  bee-capture: false
  # Throw concrete powder into a cauldron to turn it into concrete.
  cauldron-concrete:
    toggle: false
    # Whether the cauldron should use a water level on conversion.
    use-water: false
  # Throw dirt into a cauldron to turn it into mud.
  cauldron-mud:
    toggle: false
    # Whether the cauldron should use a water level on conversion.
    use-water: false
  # Allows players to bone meal any crop.
  crops-bone-meal: false
  # Right-click crops with a hoe to harvest them.
  crops-harvest: false
  # Breaking grass or flowers with a hoe will 3x3 break them. Netherite hoes will 5x5 break them.
  crops-lawn-mower: false
  # Prevents the trampling of crops.
  crops-protection: false
  # Deepslate breaks instantly when mined with a netherite pickaxe, efficiency 5, and haste 2.
  deepslate-break: false
  # Double doors can be opened with 1 click.
  doors-double: false
  # Allows you to open iron doors with your hand.
  # This works with the 'doors-double' option above!
  doors-iron: false
  # Breaking blocks nearby will cause their item drops to go towards the player a little.
  # This means if you are building high up, you won't lose all your drops.
  drops-magnet: false
  # Lapis stays in the lapis slot in enchanting tables when you close it.
  enchanting-lapis: false
  # Allows the dying of named mobs with dyes.
  entity-dye: false
  # If a player throws an item close to an entity, they will auto equip it.
  entity-equip: false
  # Right-click an entity with a flint & steel or fire charge to set it on fire.
  entity-ignite: false
  # Glass breaks instantly when broken by the materials below.
  glass-break:
    toggle: false
    materials:
      - NETHERITE_PICKAXE
  # Blocks can now be placed on the top of happy ghast's heads.
  happy-ghast-placement: false
  # Happy ghasts will now fly faster than normal (only while riding).
  happy-ghast-speed:
    toggle: false
    # Speed value of riding happy ghast.
    value: 1.5
  # Right-clicking a hay bale with a hoe automatically crafts and drops bread.
  hay-bale-bread: false
  # Allows you to view the statistics (health-speed-jump) of horses by sneak-right-click.
  # This lets you find the best horses without having to tame them all first! :)
  horse-statistics:
    toggle: false
    message:
      - "&7Max Health: &e{health}"
      - "&7Speed: &e{speed}"
      - "&7Jump: &e{jump}"
  # Right-clicking a crafting table in your inventory opens it.
  inventory-crafting: false
  # Right-clicking an item frame on a chest will open the chest. Shift to go back to normal behavior.
  item-frame-click-through: false
  # Shift-right-click an item frame with shears to make it invisible. Do it again to make it visible.
  item-frame-invisible: false
  # Allows you to place ladders up/down depending on your direction by right-clicking existing ladders.
  ladder-placement: false
  # Allows you to instantly climb up/down ladders.
  ladder-teleportation:
    toggle: false
    # Options:
    # - Automatic (simply walk into the ladder)
    # - Manual (look straight up/down to activate teleportation)
    control: Automatic
  # Breaking leaves with a hoe will break an additional block on each side. Netherite hoes will do a full 3x3x3 break.
  leaf-cutter: false
  # Nether portals can no longer be destroyed by explosions.
  # No more ghasts or creepers destroying them!
  portal-protection: false
  # Players who join the server will have all the recipes unlocked.
  # If you accidentally kept this on and didn't want this, just do '/tweaks resetrecipes'.
  recipe-unlock-all: false
  # Throwing snowballs on existing snow layers will add snow layers.
  snowballs-add-snow-layer: false
  # Throwing snowballs on plants or flowers will break them.
  snowballs-break-plants: false
  # Allows snowballs to inflict damage.
  snowballs-damage:
    toggle: false
    # Amount of damage that snowballs inflict.
    amount: 1
  # Throwing snowballs on entities will extinguish them.
  snowballs-extinguish-entities: false
  # Throwing snowballs on fire will extinguish it.
  snowballs-extinguish-fire: false
  # Throwing snowballs on water will freeze it.
  snowballs-form-ice: false
  # Throwing snowballs on any block will form snow.
  snowballs-form-snow: false
  # Changes the knockback of snowballs.
  snowballs-knockback:
    toggle: false
    # Amount of knockback that snowballs inflict.
    amount: 0.5
  # Setting a sponge on fire dries it out instantly.
  sponge-ignite: false
  # Allows you to throw torches on the ground to place them.
  # So if you throw them down a cave, it will light the block it lands on!
  torch-throw: false
  # Allows vehicles to be picked up by sneak-right-click.
  vehicle-pickup: false
  # Splashing a water bottle into lava converts it into obsidian.
  water-bottle-convert-lava: false
  # Allows you to convert a water bucket into splash water bottles.
  water-bottle-craft:
    toggle: false
    # Amount of splash water bottles you get.
    amount: 4
  # Allows weapons (swords/axes) to swing through grass without destroying them.
  weapon-swing-through-grass: false
  # Allows the filling of empty bottles into XP bottles by right-clicking on an enchanting table.
  xp-fill:
    toggle: false
    # Amount of XP it takes to fill each bottle.
    # In vanilla Minecraft, an XP bottle drops an average of 7 experience.
    cost: 8

# Random admin stuff. No need to mess with this!
reloaded: "&2&l✓ &a&lTweaky &ahas been reloaded. Registered &l{amount} &atweaks."
reset-recipes: "&2&l✓ &aRecipes have been reset for all online players."
no-permission: "&4&l❌ &cYou lack the required permission for this command."

# Allows us to collect anonymous data about the plugin.
enable-metrics: true
